# Generated by Django 3.2 on 2023-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(max_length=20)),
                ('ename', models.CharField(max_length=255)),
                ('esal', models.FloatField(max_length=20)),
                ('eaddr', models.CharField(max_length=255)),
            ],
        ),
    ]
